const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktopWidget", {
  launcherStart: () => ipcRenderer.invoke("launcher-start"),
  launcherOpenConfig: () => ipcRenderer.invoke("launcher-open-config"),
  launcherOpenAbout: () => ipcRenderer.invoke("launcher-open-about"),
  launcherImportAvatar: () => ipcRenderer.invoke("launcher-import-avatar"),
  getAvatarLibrary: () => ipcRenderer.invoke("get-avatar-library"),
  selectAvatarLibrary: (id) => ipcRenderer.invoke("select-avatar-library", { id }),
  deleteAvatarLibrary: (id) => ipcRenderer.invoke("delete-avatar-library", { id }),
  exportAvatarLibrary: (id) => ipcRenderer.invoke("export-avatar-library", { id }),
  launcherQuit: () => ipcRenderer.send("quit-app"),
  startDrag: (screenX, screenY) => ipcRenderer.send("start-drag", { screenX, screenY }),
  dragMove: (screenX, screenY) => ipcRenderer.send("drag-move", { screenX, screenY }),
  endDrag: () => ipcRenderer.send("end-drag"),
  hideAvatar: () => ipcRenderer.send("hide-avatar"),
  showAvatar: () => ipcRenderer.send("show-avatar"),
  hideControls: () => ipcRenderer.send("hide-controls"),
  showControls: () => ipcRenderer.send("show-controls"),
  showLauncher: () => ipcRenderer.send("show-launcher"),
  quitApp: () => ipcRenderer.send("quit-app"),
  resetAvatarWindowPosition: () => ipcRenderer.send("reset-avatar-window-position"),
  setAvatarWindowSize: (preset) => ipcRenderer.send("set-avatar-window-size", { preset }),
  toggleAvatarAlwaysOnTop: () => ipcRenderer.send("toggle-avatar-always-on-top"),
  toggleAvatarClickThrough: () => ipcRenderer.send("toggle-avatar-click-through"),
  refreshTrayMenu: () => ipcRenderer.send("refresh-tray-menu"),
  sendAvatarCommand: (payload) => ipcRenderer.send("avatar-command", payload),
  getWindowState: () => ipcRenderer.invoke("get-window-state"),
  onWindowState: (callback) => ipcRenderer.on("window-state", (_event, value) => callback(value)),
  onAvatarCommand: (callback) => ipcRenderer.on("avatar-command", (_event, payload) => callback(payload)),

  saveTextFileNative: (payload) => ipcRenderer.invoke("save-text-file-native", payload),
  openTextFileNative: () => ipcRenderer.invoke("open-text-file-native"),
  setThemeSourceNative: (theme) => ipcRenderer.invoke("set-theme-source-native", { theme }),
  getDesktopEnvironment: () => ipcRenderer.invoke("get-desktop-environment"),

  importAvatarVrmNative: () => ipcRenderer.invoke("import-avatar-vrm-native"),
  getAvatarDiagnostics: () => ipcRenderer.invoke("get-avatar-diagnostics"),
  getAvatarRuntimeUrl: () => ipcRenderer.invoke("get-avatar-runtime-url"),
  getAvatarRuntimeUrlSync: () => ipcRenderer.sendSync("get-avatar-runtime-url-sync"),
  getStructureSnapshot: () => ipcRenderer.invoke("get-structure-snapshot"),
  reloadAvatarWindow: () => ipcRenderer.send("reload-avatar-window"),

  assetExists: (relPath) => ipcRenderer.invoke("asset-exists", { relPath }),
  readJsonAsset: (relPath) => ipcRenderer.invoke("read-json-asset", { relPath }),
  getAssetFileUrl: (relPath) => ipcRenderer.invoke("get-asset-file-url", { relPath }),

  // NoelleCore IA local integrada via Ollama. A UI fala com o processo principal,
  // e o processo principal controla modelo, perfil, memória e segurança de PC fraco.
  noelleCoreStatus: () => ipcRenderer.invoke("noelle-core-status"),
  noelleCoreChat: (payload) => ipcRenderer.invoke("noelle-core-chat", payload),
  noelleCoreSetModel: (mode) => ipcRenderer.invoke("noelle-core-set-model", { mode }),
  noelleCoreSetProfile: (profile) => ipcRenderer.invoke("noelle-core-set-profile", { profile }),
  noelleCoreSetPersona: (persona) => ipcRenderer.invoke("noelle-core-set-persona", { persona }),
  noelleCoreSpeak: (text, options) => ipcRenderer.invoke("noelle-core-speak", { text, options }),
  noelleCoreUnload: () => ipcRenderer.invoke("noelle-core-unload"),
  noelleCorePreload: () => ipcRenderer.invoke("noelle-core-preload"),
  noelleCoreReset: (sessionId) => ipcRenderer.invoke("noelle-core-reset", { session_id: sessionId }),
  noelleCoreRemember: (text) => ipcRenderer.invoke("noelle-core-remember", { text }),
  noelleCoreMemories: () => ipcRenderer.invoke("noelle-core-memories"),
  noelleCoreForgetMemory: (target = "last") => ipcRenderer.invoke("noelle-core-forget-memory", { target }),
  noelleCoreClearMemories: () => ipcRenderer.invoke("noelle-core-clear-memories"),
  noelleCoreBench: () => ipcRenderer.invoke("noelle-core-bench"),
  noelleCoreDiagnostic: () => ipcRenderer.invoke("noelle-core-diagnostic"),
  noelleCoreTranscribeAudio: (payload) => ipcRenderer.invoke("noelle-core-transcribe-audio", payload),
});
